---
- hosts: all
  become: true
  tasks:
# sudo group setup
    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo    ALL=(ALL)   NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

# Install packages
    - name: Update apt
      apt: update_cache=yes

    - name: Install dependencies
      apt:
        pkg:
          - curl
          - vim
          - git
          - build-essential
          - software-properties-common
          - libvirt-clients
          - libvirt-daemon-system
          - ovmf
          - virt-manager
          - qemu-system-x86
        state: latest

# /usr/bin/ansible invocations
# ansible host -m virt -a "name=<vm_name> command=status"
# ansible host -m virt -a "name=alpha command=get_xml"
# ansible host -m virt -a "name=alpha command=create uri=lxc:///"

# Setup VMs
    - name: Setup VMs
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'container-template.xml.j2') }}"
        url: 'lxc:///'
    - name: Start VM
      community.libvirt.virt:
        name: <VM_Name>
        state: running
        autostart: yes
    - name: List running VMs
      community.libvirt.virt:
        command: list_vms
        state: running
      register: running_vms
...
